### ISSUE TITLE
Expired Certificate

### ISSUE THREAD

**Issue by lezwright** [Leo4815162342/dukascopy-tools#13]
Hi Leo, A new issue happening from today. 
![image](https://user-images.githubusercontent.com/61321682/83326568-f2174380-a26c-11ea-9ddb-59cae68c4be0.png)

Please can you let me know what is going on?

**Comment by Leo4815162342** [comment]
@lezwright looks like dukascopy datafeed is not accepting (for some reason) the default user agent params that we send via our fetch request. Can you share the exact request config with which the error is happening?

**Comment by lezwright** [comment]
Oh, thank you for getting back to me. Here is the detail:


getHistoricRates({
  instrument: 'eurcad',
  dates: {
    from: '2018-01-01',
    to: '2020-01-01'
  },
  timeframe: 'h1',
  format: 'json'
}).then(data => {
  console.log(data);
}).catch(error => {
    console.log('error', error);
});

And here is the exact error message:


error { FetchError: request to https://datafeed.dukascopy.com/datafeed/EURCAD/2018/01/BID_candles_hour_1.bi5 failed, reason: certificate has expired
    at ClientRequest.<anonymous> (/Desktop/Data/tradingview-udf-binance-node/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:180:13)
    at ClientRequest.emit (domain.js:422:20)
    at TLSSocket.socketErrorListener (_http_client.js:395:9)
    at TLSSocket.emit (events.js:180:13)
    at TLSSocket.emit (domain.js:422:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
  message: 'request to https://datafeed.dukascopy.com/datafeed/EURCAD/2018/01/BID_candles_hour_1.bi5 failed, reason: certificate has expired',
  type: 'system',
  errno: 'CERT_HAS_EXPIRED',
  code: 'CERT_HAS_EXPIRED' }


Just one more piece of information, I tested it with a different IP address and it worked. But from my server IP address it does not work.

**Comment by Leo4815162342** [comment]
@lezwright thanks, in this case it might me something related to the environment from which the call is firing. The only difference is the IP? Anything else? 

Can you also check the node version? (via `node -v`).

**Comment by lezwright** [comment]
Version of node is v9.11.2

**Comment by lezwright** [comment]
The other node that I get successful call is v12.16.1

**Comment by lezwright** [comment]
I didn't have any problems until this morning. It suddenly started giving me this message.

**Comment by lezwright** [comment]
Any suggestion?

**Comment by Leo4815162342** [comment]
first you can try updating node

**Comment by lezwright** [comment]
I am a bit scared with messing with Linux. Are the following steps correct to take? 

sudo add-apt-repository ppa:chris-lea/node.js  
sudo apt-get update  
sudo apt-get install node


I am using  Ubuntu 14.04.6 .

**Comment by lezwright** [comment]
Oh God, it is working. Thanks. So the problem at this stage was Node version :-) Thank you very much.
