### ISSUE TITLE
More Time Frames

### ISSUE THREAD

**Issue by lezwright** [Leo4815162342/dukascopy-tools#14]
Hi Leo, Thank you very much for your helps. Is it possible for you to add more time frames like 4 hours or 1 week?

**Comment by Leo4815162342** [comment]
Hey, it should be doable. I’ll let you know when I add those

**Comment by straitsboy** [comment]
Hi Leo, could you also add the 5-minute timeframe?

Thank you.

**Comment by Leo4815162342** [comment]
@straitsboy I'll try to work on it for the next release

**Comment by kevin-bruton** [comment]
I give another upvote for adding the 5 min and 4 hour timeframes.
By the way, great project!

**Comment by Leo4815162342** [comment]
@kevin-bruton @straitsboy @lezwright sorry for the delayed release.

I've added `m5` and `h4` timeframe -  https://github.com/Leo4815162342/dukascopy-tools/pull/53
You can update the version of `dukascopy-node` to `1.11.0` - https://www.npmjs.com/package/dukascopy-node/v/1.11.0

Let me know if you experience any issue with it
