### ISSUE TITLE
Wierd outputs from timeframes

### ISSUE THREAD

**Issue by Dwyte** [Leo4815162342/dukascopy-tools#15]
On intraday timeframes like m1 or m5, I tried downloading there are a bunch of candles that have the same value ohlc like same 132.2301 on open high low close, some of em are only same high low close, and it's alot like a big chunk of the whole series is like that then back to normal.

Also on D1, there are saturday candles, where are these coming from? Forex Markets are closed during saturday right. 

I have encountered the problem weeks ago on the first one, I forgot to raise an issue, I just started writing a small py script to form the candles from tick hehe

**Comment by Leo4815162342** [comment]
@Dwyte those might indeed come from weekends or non-trading days. Can you share the exact search config?

**Comment by Dwyte** [comment]
Sorry for the late reply, `dukascopy-cli -i eurusd -from 2020-02-24 -to 2020-05-16 -t m1 -f csv` to replicate, and see here the issue from the result https://imgur.com/a/AbDZb20

**Comment by Leo4815162342** [comment]
For `m1` timeframe dukascopy still returns data for non-trading time. It populates all entries with the last close price of the trading window.

I've added a small fix so it does not output such entries. Please update `dukascopy-cli` to `1.2.1` version.
