### ISSUE TITLE
ducascopy-cli command not found on windows

### ISSUE THREAD

**Issue by nimo862** [Leo4815162342/dukascopy-tools#22]
Hello, thank you for this useful tool.
I installed ducascopy-cli on Windows 10 with the command 
`npm install dukascopy-cli --save-dev`

but when I try to use it, it gives me the error:
`ducascopy-cli not recognized as an internal or external command`

How can I resolve the problem?
Thanks

**Comment by Leo4815162342** [comment]
@nimo862 can you try running `npx ducascopy-cli`?

**Comment by nimo862** [comment]
> @nimo862 can you try running `npx ducascopy-cli`?
> for example: `npx dukascopy-cli -i eurusd -from 2006-01-01 -to 2020-01-01 -t d1 -f json`

Thanks! It worked
