### ISSUE TITLE
please provide reason for some instruments

### ISSUE THREAD

**Issue by Roskosh** [Leo4815162342/dukascopy-tools#23]
Hi! Great project! Can you please enlighten me how to use ticks for US equity from dukascopy? I've found that this ticks perhaps just so called "best bid/ask offer" (or Level 1 type of tick data) and clearly not "trade bid/ask". You can see it bid always not equals ask.

**Comment by Leo4815162342** [comment]
That's a good question. Since my package only mirrors whatever is available in dukascopy archives, they might be a better source for clearing your question

**Comment by Roskosh** [comment]
Leonid, thank you!
 
With best wishes, Vlad
