### ISSUE TITLE
Need processing from local disk not from Dukascopy Server

### ISSUE THREAD

**Issue by extremk** [Leo4815162342/dukascopy-tools#28]
Need processing from local disk not from Dukascopy Server
Data already downloaded

**Comment by Leo4815162342** [comment]
Yeap, that is a legit concern. I was thinking to introduce a file cache for that, in order not to download data files that have already been previously requested/downloaded

**Comment by Leo4815162342** [comment]
@extremk we've published a new version  that introduces a file system cache - with it, the subsequent requests for similar data or date ranges will not go through dukascopy servers and will be resolved from local file system cache:

* `dukascopy-node` - `1.5.0` (`useCache` parameter - see docs https://github.com/Leo4815162342/dukascopy-tools/tree/master/packages/dukascopy-node#config-object) 
* `dukascopy-cli` - `1.4.0` (`--cache` flag - see docs https://github.com/Leo4815162342/dukascopy-tools/tree/master/packages/dukascopy-cli#options)
