### ISSUE TITLE
Please add an option：skip bad data and do not stop converting

### ISSUE THREAD

**Issue by extremk** [Leo4815162342/dukascopy-tools#29]
Please add an option：skip bad data and do not stop converting
I Need this option

**Comment by Leo4815162342** [comment]
@extremk how would do you define bad data?

**Comment by extremk** [comment]
![image](https://user-images.githubusercontent.com/12088131/108586516-061a4c80-738a-11eb-917f-5b4096936d46.png)

**Comment by extremk** [comment]
![image](https://user-images.githubusercontent.com/12088131/108586671-f0595700-738a-11eb-8a13-419e2b7134a2.png)

**Comment by Leo4815162342** [comment]
@extremk thanks for the screenshots, I'll take a look and try to patch it

**Comment by extremk** [comment]
Please fix this program.
According to my test, all the quotations are not completely normal，the program will go wrong.

dukascopy-cli -i ussc2000idxusd -from 2018-06-01 -to 2018-06-02 -t tick -fl true -f csv
from 2018-06-01 to 2018-06-02  
All quotations are flat, the program does not get any data, the program will report an error
Cannot read property '0' of undefined

dukascopy-cli -i xxxx(many Symbols) -from 2000-01-01 -to 2001-01-01 -t tick -f csv
The start and end times are the same day, or not within the legal range, so that the start and end times become the same day, and the program will fail

The program downloaded Bi5 has decompression errors,it will stop running, and I hope to continue running even if  errors

**Comment by Leo4815162342** [comment]
@extremk  the issue with empty binary files has been fixed and new version has been  published. Please update `dukascopy-cli` to version `1.3.2`.

Regarding `dukascopy-cli -i xxxx(many Symbols) -from 2000-01-01 -to 2001-01-01 -t tick -f csv`:
when downloading tick data, please use lower time ranges, year worth of tick data with one call will most likely fail, as dukascopy servers are most probably rate-limit the requests.
