### ISSUE TITLE
Please add missing pairs

### ISSUE THREAD

**Issue by extremk** [Leo4815162342/dukascopy-tools#31]
These pairs exist on the server, but your software has not been added to support them
H1 start List below:

AABAUSUSD\AABAUSUSD_2017.bi5
AABAUSUSD\AABAUSUSD_2018.bi5
AABAUSUSD\AABAUSUSD_2019.bi5
AABAUSUSD\AABAUSUSD_2020.bi5
AETUSUSD\AETUSUSD_2017.bi5
AETUSUSD\AETUSUSD_2018.bi5
AETUSUSD\AETUSUSD_2019.bi5
AETUSUSD\AETUSUSD_2020.bi5
APCUSUSD\APCUSUSD_2017.bi5
APCUSUSD\APCUSUSD_2018.bi5
APCUSUSD\APCUSUSD_2019.bi5
APCUSUSD\APCUSUSD_2020.bi5
BBTUSUSD\BBTUSUSD_2018.bi5
BBTUSUSD\BBTUSUSD_2019.bi5
BBTUSUSD\BBTUSUSD_2020.bi5
CBSUSUSD\CBSUSUSD_2018.bi5
CBSUSUSD\CBSUSUSD_2019.bi5
CBSUSUSD\CBSUSUSD_2020.bi5
CELGUSUSD\CELGUSUSD_2017.bi5
CELGUSUSD\CELGUSUSD_2018.bi5
CELGUSUSD\CELGUSUSD_2019.bi5
CELGUSUSD\CELGUSUSD_2020.bi5
COLUSUSD\COLUSUSD_2017.bi5
COLUSUSD\COLUSUSD_2018.bi5
COLUSUSD\COLUSUSD_2019.bi5
COLUSUSD\COLUSUSD_2020.bi5
ESRXUSUSD\ESRXUSUSD_2017.bi5
ESRXUSUSD\ESRXUSUSD_2018.bi5
ESRXUSUSD\ESRXUSUSD_2019.bi5
ESRXUSUSD\ESRXUSUSD_2020.bi5
HCPUSUSD\HCPUSUSD_2018.bi5
HCPUSUSD\HCPUSUSD_2019.bi5
HCPUSUSD\HCPUSUSD_2020.bi5
PXUSUSD\PXUSUSD_2018.bi5
RHTUSUSD\RHTUSUSD_2018.bi5
RRSGBGBX\RRSGBGBX_2011.bi5
RRSGBGBX\RRSGBGBX_2012.bi5
RRSGBGBX\RRSGBGBX_2013.bi5
RRSGBGBX\RRSGBGBX_2014.bi5
RRSGBGBX\RRSGBGBX_2015.bi5
RRSGBGBX\RRSGBGBX_2016.bi5
RRSGBGBX\RRSGBGBX_2017.bi5
RRSGBGBX\RRSGBGBX_2018.bi5
RRSGBGBX\RRSGBGBX_2019.bi5
RRSGBGBX\RRSGBGBX_2020.bi5
RTNUSUSD\RTNUSUSD_2018.bi5
RTNUSUSD\RTNUSUSD_2019.bi5
RTNUSUSD\RTNUSUSD_2020.bi5
STIUSUSD\STIUSUSD_2018.bi5
STIUSUSD\STIUSUSD_2019.bi5
STIUSUSD\STIUSUSD_2020.bi5
SYMCUSUSD\SYMCUSUSD_2018.bi5
SYMCUSUSD\SYMCUSUSD_2019.bi5
SYMCUSUSD\SYMCUSUSD_2020.bi5
UTXUSUSD\UTXUSUSD_2017.bi5
UTXUSUSD\UTXUSUSD_2018.bi5
UTXUSUSD\UTXUSUSD_2019.bi5
UTXUSUSD\UTXUSUSD_2020.bi5
VIABUSUSD\VIABUSUSD_2018.bi5
VIABUSUSD\VIABUSUSD_2019.bi5
VIABUSUSD\VIABUSUSD_2020.bi5

Please add them to the software

**Comment by extremk** [comment]
[Download.zip](https://github.com/Leo4815162342/dukascopy-tools/files/6064098/Download.zip)

**Comment by Leo4815162342** [comment]
@extremk thank you - I'll try to add those.
Originally, I took the list of instruments from here: https://www.dukascopy.com/trading-tools/widgets/quotes/historical_data_feed
I did not know there were more.

**Comment by Leo4815162342** [comment]
@extremk also, how did you find those instruments?

**Comment by tallm0cha** [comment]
Disclaimer: I am not an expert coder and haven't delved into the internals of the dukascopy-cli has been built. Not that it isn't the best package on github to get dukascopy data :)

A suggestion would be to not put any limits on the instrument name. If the server doesn't have it, throw an error and put the onus on the user. The same link you mentioned (https://www.dukascopy.com/trading-tools/widgets/quotes/historical_data_feed) has the additional instruments. I reckon the list is constantly updated so removing the dependency will likely help in future-proofing.

**Comment by Leo4815162342** [comment]
@tallm0cha thanks for the feedback. Yes, we indeed have strict validation rules, especially when It comes to the instrument name. But  I agree about the ideas of future-proofing it.

I’ll see what we can do to make make validation less strict

**Comment by extremk** [comment]
> @extremk also, how did you find those instruments?

From a list I downloaded a few months ago

**Comment by Leo4815162342** [comment]
In order to add new instruments, we'll need meta data on them first. I'll need first to understand how to generate it. Closing this for now.
