### ISSUE TITLE
Easy fix: second-resolution data download

### ISSUE THREAD

**Issue by yash-browncs** [Leo4815162342/dukascopy-tools#55]
At [this link](https://www.dukascopy.com/trading-tools/widgets/quotes/historical_data_feed), there is an option to download bid/ask data in second resolution (1s, 15s, 30s, etc.), but there's no support for this in the `dukascopy-cli` tool. I believe there can be more timestamp resolutions added between tick and 1 minute.

**Comment by Leo4815162342** [comment]
@yash-browncs that's a good idea. We've never had a use case for resolutions in seconds before. I'll try to prepare it for the next release.
