### ISSUE TITLE
Fifteen Minute

### ISSUE THREAD

**Issue by lezwright** [Leo4815162342/dukascopy-tools#9]
Hi Leo, 

Could you please add the fifteen minute data to the library as well? 

Many thanks.

**Comment by Leo4815162342** [comment]
@lezwright I'll have a look, it should be not that difficult to add

**Comment by Leo4815162342** [comment]
@lezwright I've released an update which includes 15-minute timeframe `m15`.
See: `^dukascopy-node@1.3.0`

**Comment by lezwright** [comment]
Many thanks Leo!
